export const SCREENS_NAME = {
  HOME_NAVIGATOR: 'Danh sách đơn hàng ',
  LIST_ORDER: 'Danh sách đơn hàng',
  DETAIL_ORDER_WAITING: 'Chi tiết đơn hàng trả lại',
  DETAIL_ORDER_INFO: 'Chi tiết đơn hàng',
  DETAIL_WAITING_FOR_IT: 'Chi tiết đơn hàng chờ lấy',
  DETAIL_WAITING_DELIVEY: 'Chi tiết đơn hàng chờ giao',
  DETAIL_DELIVERD: 'Chi tiết đơn hàng đã giao',
  LOGIN: 'Đăng nhập',
  BARCODE_SCAN: 'Quét mã',
  END_TRIP: 'Nộp tiền',
  STATISTIC: 'Thống kê',
  SUCCESS_INFO: 'Năng suất',
  TRIP_INFO: 'Chuyến đi',
};
